[package]
name = "Lab1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
csv = "1.2.2"
bit-set = { version = "0.5.2", features = [] }
rayon = { version = "1.5.1", features = [] }
